use crate::sim::Handler;
use crate::ops::typed::TypedHandler;
use crate::isa::types::DataType;
use crate::ops::typed_mem_ops::TypedMemHandler;
use crate::ops::typed_s_ops::TypedSHandler;
use crate::ops::typed_v_ops::TypedVHandler;
use crate::ops::typed_v_ops::BinaryOp;

pub mod manual_v_ops;
pub mod manual_s_ops;
pub mod manual_mem_ops;
pub mod manual_misc_ops;

pub static OPS: &[(&str, Handler)] = &[
  ("buffer_atomic_cmpswap_f32", manual_mem_ops::buffer_atomic_cmpswap_f32),
  ("buffer_atomic_csub_u32", manual_mem_ops::buffer_atomic_csub_u32),
  ("buffer_load_lds_format_x", manual_mem_ops::buffer_load_lds_format_x),
  ("ds_add_gs_reg_rtn", manual_mem_ops::ds_add_gs_reg_rtn),
  ("ds_bvh_stack_rtn_b32", manual_mem_ops::ds_bvh_stack_rtn_b32),
  ("ds_cmpstore_f32", manual_mem_ops::ds_cmpstore_f32),
  ("ds_cmpstore_rtn_f32", manual_mem_ops::ds_cmpstore_rtn_f32),
  ("ds_gws_barrier", manual_mem_ops::ds_gws_barrier),
  ("ds_gws_init", manual_mem_ops::ds_gws_init),
  ("ds_gws_sema_br", manual_mem_ops::ds_gws_sema_br),
  ("ds_gws_sema_p", manual_mem_ops::ds_gws_sema_p),
  ("ds_gws_sema_release_all", manual_mem_ops::ds_gws_sema_release_all),
  ("ds_gws_sema_v", manual_mem_ops::ds_gws_sema_v),
  ("ds_ordered_count", manual_mem_ops::ds_ordered_count),
  ("ds_sub_gs_reg_rtn", manual_mem_ops::ds_sub_gs_reg_rtn),
  ("ds_wrap_rtn_b32", manual_mem_ops::ds_wrap_rtn_b32),
  ("flat_atomic_cmpswap_f32", manual_mem_ops::flat_atomic_cmpswap_f32),
  ("global_atomic_cmpswap_f32", manual_mem_ops::global_atomic_cmpswap_f32),
  ("global_atomic_csub_u32", manual_mem_ops::global_atomic_csub_u32),
  ("global_load_addtid_b32", manual_mem_ops::global_load_addtid_b32),
  ("global_load_b128", manual_mem_ops::global_load_b128),
  ("global_load_b32", manual_mem_ops::global_load_b32),
  ("global_load_b64", manual_mem_ops::global_load_b64),
  ("global_load_b96", manual_mem_ops::global_load_b96),
  ("global_load_d16_b16", manual_mem_ops::global_load_d16_b16),
  ("global_load_d16_hi_b16", manual_mem_ops::global_load_d16_hi_b16),
  ("global_load_lds_addtid_b32", manual_mem_ops::global_load_lds_addtid_b32),
  ("global_load_lds_b32", manual_mem_ops::global_load_lds_b32),
  ("global_store_addtid_b32", manual_mem_ops::global_store_addtid_b32),
  ("global_store_b128", manual_mem_ops::global_store_b128),
  ("global_store_b16", manual_mem_ops::global_store_b16),
  ("global_store_b32", manual_mem_ops::global_store_b32),
  ("global_store_b64", manual_mem_ops::global_store_b64),
  ("global_store_b8", manual_mem_ops::global_store_b8),
  ("global_store_b96", manual_mem_ops::global_store_b96),
  ("global_store_d16_hi_b16", manual_mem_ops::global_store_d16_hi_b16),
  ("global_store_d16_hi_b8", manual_mem_ops::global_store_d16_hi_b8),
  ("image_atomic_add", manual_mem_ops::image_atomic_add),
  ("image_atomic_dec", manual_mem_ops::image_atomic_dec),
  ("image_atomic_inc", manual_mem_ops::image_atomic_inc),
  ("image_atomic_smax", manual_mem_ops::image_atomic_smax),
  ("image_atomic_smin", manual_mem_ops::image_atomic_smin),
  ("image_atomic_sub", manual_mem_ops::image_atomic_sub),
  ("image_atomic_umax", manual_mem_ops::image_atomic_umax),
  ("image_atomic_umin", manual_mem_ops::image_atomic_umin),
  ("lds_direct_load", manual_misc_ops::lds_direct_load),
  ("lds_param_load", manual_misc_ops::lds_param_load),
  ("s_addc_u32", manual_s_ops::s_addc_u32),
  ("s_addk_i32", manual_s_ops::s_addk_i32),
  ("s_atc_probe", manual_s_ops::s_atc_probe),
  ("s_atc_probe_buffer", manual_s_ops::s_atc_probe_buffer),
  ("s_barrier", manual_s_ops::s_barrier),
  ("s_cbranch_cdbgsys", manual_s_ops::s_cbranch_cdbgsys),
  ("s_cbranch_cdbgsys_and_user", manual_s_ops::s_cbranch_cdbgsys_and_user),
  ("s_cbranch_cdbgsys_or_user", manual_s_ops::s_cbranch_cdbgsys_or_user),
  ("s_cbranch_cdbguser", manual_s_ops::s_cbranch_cdbguser),
  ("s_cvt_f16_f32", manual_s_ops::s_cvt_f16_f32),
  ("s_cvt_hi_f32_f16", manual_s_ops::s_cvt_hi_f32_f16),
  ("s_cvt_i32_f32", manual_s_ops::s_cvt_i32_f32),
  ("s_cvt_pk_rtz_f16_f32", manual_s_ops::s_cvt_pk_rtz_f16_f32),
  ("s_cvt_u32_f32", manual_s_ops::s_cvt_u32_f32),
  ("s_endpgm_ordered_ps_done", manual_s_ops::s_endpgm_ordered_ps_done),
  ("s_fmaak_f32", manual_s_ops::s_fmaak_f32),
  ("s_fmamk_f32", manual_s_ops::s_fmamk_f32),
  ("s_gl1_inv", manual_s_ops::s_gl1_inv),
  ("s_set_inst_prefetch_distance", manual_s_ops::s_set_inst_prefetch_distance),
  ("s_subb_u32", manual_s_ops::s_subb_u32),
  ("s_waitcnt", manual_s_ops::s_waitcnt),
  ("s_waitcnt_depctr", manual_s_ops::s_waitcnt_depctr),
  ("s_waitcnt_expcnt", manual_s_ops::s_waitcnt_expcnt),
  ("s_waitcnt_lgkmcnt", manual_s_ops::s_waitcnt_lgkmcnt),
  ("s_waitcnt_vmcnt", manual_s_ops::s_waitcnt_vmcnt),
  ("s_waitcnt_vscnt", manual_s_ops::s_waitcnt_vscnt),
  ("scratch_load_b128", manual_misc_ops::scratch_load_b128),
  ("scratch_load_b32", manual_misc_ops::scratch_load_b32),
  ("scratch_load_b64", manual_misc_ops::scratch_load_b64),
  ("scratch_load_b96", manual_misc_ops::scratch_load_b96),
  ("scratch_load_d16_b16", manual_misc_ops::scratch_load_d16_b16),
  ("scratch_load_d16_hi_b16", manual_misc_ops::scratch_load_d16_hi_b16),
  ("scratch_load_d16_hi_i8", manual_misc_ops::scratch_load_d16_hi_i8),
  ("scratch_load_d16_hi_u8", manual_misc_ops::scratch_load_d16_hi_u8),
  ("scratch_load_d16_i8", manual_misc_ops::scratch_load_d16_i8),
  ("scratch_load_d16_u8", manual_misc_ops::scratch_load_d16_u8),
  ("scratch_load_i16", manual_misc_ops::scratch_load_i16),
  ("scratch_load_i8", manual_misc_ops::scratch_load_i8),
  ("scratch_load_lds_b32", manual_misc_ops::scratch_load_lds_b32),
  ("scratch_load_lds_i16", manual_misc_ops::scratch_load_lds_i16),
  ("scratch_load_lds_i8", manual_misc_ops::scratch_load_lds_i8),
  ("scratch_load_lds_u16", manual_misc_ops::scratch_load_lds_u16),
  ("scratch_load_lds_u8", manual_misc_ops::scratch_load_lds_u8),
  ("scratch_load_u16", manual_misc_ops::scratch_load_u16),
  ("scratch_load_u8", manual_misc_ops::scratch_load_u8),
  ("scratch_store_b128", manual_misc_ops::scratch_store_b128),
  ("scratch_store_b16", manual_misc_ops::scratch_store_b16),
  ("scratch_store_b32", manual_misc_ops::scratch_store_b32),
  ("scratch_store_b64", manual_misc_ops::scratch_store_b64),
  ("scratch_store_b8", manual_misc_ops::scratch_store_b8),
  ("scratch_store_b96", manual_misc_ops::scratch_store_b96),
  ("scratch_store_d16_hi_b16", manual_misc_ops::scratch_store_d16_hi_b16),
  ("scratch_store_d16_hi_b8", manual_misc_ops::scratch_store_d16_hi_b8),
  ("v_dot2acc_f32_f16", manual_v_ops::v_dot2acc_f32_f16),
  ("v_dual_max_f32", manual_v_ops::v_dual_max_f32),
  ("v_dual_min_f32", manual_v_ops::v_dual_min_f32),
  ("v_fmac_dx9_zero_f32", manual_v_ops::v_fmac_dx9_zero_f32),
  ("v_mad_i64_i32", manual_v_ops::v_mad_i64_i32),
  ("v_mad_u64_u32", manual_v_ops::v_mad_u64_u32),
];

pub static TYPED_OPS: &[(&str, TypedHandler)] = &[
  ("buffer_atomic_max_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("buffer_atomic_min_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("ds_max_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("ds_max_rtn_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("ds_min_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("ds_min_rtn_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("flat_atomic_max_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("flat_atomic_min_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("global_atomic_max_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("global_atomic_min_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("global_load_d16_hi_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("global_load_d16_hi_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("global_load_d16_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("global_load_d16_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("global_load_i16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I16 })),
  ("global_load_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("global_load_lds_i16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I16 })),
  ("global_load_lds_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("global_load_lds_u16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U16 })),
  ("global_load_lds_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("global_load_u16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U16 })),
  ("global_load_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("s_add_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_add_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_add_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_add_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_ceil_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_ceil_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_eq_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_eq_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_ge_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_ge_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_gt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_gt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_le_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_le_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_lg_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_lg_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_lt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_lt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_neq_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_neq_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nge_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nge_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_ngt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_ngt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nle_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nle_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nlg_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nlg_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nlt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nlt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_o_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_o_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_u_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_u_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmpk_eq_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmpk_eq_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmpk_ge_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmpk_ge_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmpk_gt_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmpk_gt_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmpk_le_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmpk_le_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmpk_lg_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmpk_lg_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmpk_lt_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmpk_lt_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cvt_f32_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cvt_f32_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cvt_f32_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_floor_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_floor_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_fmac_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_fmac_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_max_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_max_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_min_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_min_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_mul_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_mul_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_rndne_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_rndne_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_sub_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_sub_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_sub_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_sub_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_trunc_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_trunc_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmp_f_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cmp_f_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmp_f_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_cmp_f_i64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I64 })),
  ("v_cmp_f_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_cmp_f_u64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U64 })),
  ("v_cmp_t_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cmp_t_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmp_t_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_cmp_t_i64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I64 })),
  ("v_cmp_t_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_cmp_t_u64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U64 })),
  ("v_cmpx_f_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cmpx_f_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmpx_f_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_cmpx_f_i64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I64 })),
  ("v_cmpx_f_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_cmpx_f_u64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U64 })),
  ("v_cmpx_t_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cmpx_t_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmpx_t_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_cmpx_t_i64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I64 })),
  ("v_cmpx_t_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_cmpx_t_u64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U64 })),
  ("v_max3_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_max3_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_max_f16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F16, op: BinaryOp::Max })),
  ("v_max_f32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F32, op: BinaryOp::Max })),
  ("v_maxmin_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_maxmin_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_med3_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_med3_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_min3_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_min3_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_min_f16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F16, op: BinaryOp::Min })),
  ("v_min_f32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F32, op: BinaryOp::Min })),
  ("v_minmax_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_minmax_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_pk_max_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_pk_min_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
];
