use crate::sim::Handler;
use crate::ops::typed::TypedHandler;
use crate::isa::types::DataType;
use crate::ops::typed_mem_ops::TypedMemHandler;
use crate::ops::typed_s_ops::TypedSHandler;
use crate::ops::typed_v_ops::TypedVHandler;

pub mod manual_v_ops;
pub mod manual_s_ops;
pub mod manual_mem_ops;

pub static OPS: &[(&str, Handler)] = &[
  ("buffer_atomic_cond_sub_u32", manual_mem_ops::buffer_atomic_cond_sub_u32),
  ("buffer_atomic_max_num_f32", manual_mem_ops::buffer_atomic_max_num_f32),
  ("buffer_atomic_min_num_f32", manual_mem_ops::buffer_atomic_min_num_f32),
  ("buffer_atomic_sub_clamp_u32", manual_mem_ops::buffer_atomic_sub_clamp_u32),
  ("buffer_load_b128", manual_mem_ops::buffer_load_b128),
  ("buffer_load_b32", manual_mem_ops::buffer_load_b32),
  ("buffer_load_b64", manual_mem_ops::buffer_load_b64),
  ("buffer_load_b96", manual_mem_ops::buffer_load_b96),
  ("buffer_load_d16_b16", manual_mem_ops::buffer_load_d16_b16),
  ("buffer_load_d16_hi_b16", manual_mem_ops::buffer_load_d16_hi_b16),
  ("buffer_store_b128", manual_mem_ops::buffer_store_b128),
  ("buffer_store_b16", manual_mem_ops::buffer_store_b16),
  ("buffer_store_b32", manual_mem_ops::buffer_store_b32),
  ("buffer_store_b64", manual_mem_ops::buffer_store_b64),
  ("buffer_store_b8", manual_mem_ops::buffer_store_b8),
  ("buffer_store_b96", manual_mem_ops::buffer_store_b96),
  ("buffer_store_d16_hi_b16", manual_mem_ops::buffer_store_d16_hi_b16),
  ("buffer_store_d16_hi_b8", manual_mem_ops::buffer_store_d16_hi_b8),
  ("ds_bpermute_fi_b32", manual_mem_ops::ds_bpermute_fi_b32),
  ("ds_bvh_stack_push4_pop1_rtn_b32", manual_mem_ops::ds_bvh_stack_push4_pop1_rtn_b32),
  ("ds_bvh_stack_push8_pop1_rtn_b32", manual_mem_ops::ds_bvh_stack_push8_pop1_rtn_b32),
  ("ds_bvh_stack_push8_pop2_rtn_b64", manual_mem_ops::ds_bvh_stack_push8_pop2_rtn_b64),
  ("ds_cond_sub_rtn_u32", manual_mem_ops::ds_cond_sub_rtn_u32),
  ("ds_cond_sub_u32", manual_mem_ops::ds_cond_sub_u32),
  ("ds_direct_load", manual_mem_ops::ds_direct_load),
  ("ds_max_num_f32", manual_mem_ops::ds_max_num_f32),
  ("ds_max_num_rtn_f32", manual_mem_ops::ds_max_num_rtn_f32),
  ("ds_min_num_f32", manual_mem_ops::ds_min_num_f32),
  ("ds_min_num_rtn_f32", manual_mem_ops::ds_min_num_rtn_f32),
  ("ds_param_load", manual_mem_ops::ds_param_load),
  ("ds_sub_clamp_rtn_u32", manual_mem_ops::ds_sub_clamp_rtn_u32),
  ("ds_sub_clamp_u32", manual_mem_ops::ds_sub_clamp_u32),
  ("flat_atomic_cond_sub_u32", manual_mem_ops::flat_atomic_cond_sub_u32),
  ("flat_atomic_max_num_f32", manual_mem_ops::flat_atomic_max_num_f32),
  ("flat_atomic_min_num_f32", manual_mem_ops::flat_atomic_min_num_f32),
  ("flat_atomic_sub_clamp_u32", manual_mem_ops::flat_atomic_sub_clamp_u32),
  ("global_atomic_cond_sub_u32", manual_mem_ops::global_atomic_cond_sub_u32),
  ("global_atomic_max_num_f32", manual_mem_ops::global_atomic_max_num_f32),
  ("global_atomic_min_num_f32", manual_mem_ops::global_atomic_min_num_f32),
  ("global_atomic_ordered_add_b64", manual_mem_ops::global_atomic_ordered_add_b64),
  ("global_atomic_sub_clamp_u32", manual_mem_ops::global_atomic_sub_clamp_u32),
  ("image_atomic_add_flt", manual_mem_ops::image_atomic_add_flt),
  ("image_atomic_add_uint", manual_mem_ops::image_atomic_add_uint),
  ("image_atomic_dec_uint", manual_mem_ops::image_atomic_dec_uint),
  ("image_atomic_inc_uint", manual_mem_ops::image_atomic_inc_uint),
  ("image_atomic_max_flt", manual_mem_ops::image_atomic_max_flt),
  ("image_atomic_max_int", manual_mem_ops::image_atomic_max_int),
  ("image_atomic_max_uint", manual_mem_ops::image_atomic_max_uint),
  ("image_atomic_min_flt", manual_mem_ops::image_atomic_min_flt),
  ("image_atomic_min_int", manual_mem_ops::image_atomic_min_int),
  ("image_atomic_min_uint", manual_mem_ops::image_atomic_min_uint),
  ("image_atomic_sub_uint", manual_mem_ops::image_atomic_sub_uint),
  ("s_add_co_ci_u32", manual_s_ops::s_add_co_ci_u32),
  ("s_add_nc_u64", manual_s_ops::s_add_nc_u64),
  ("s_addk_co_i32", manual_s_ops::s_addk_co_i32),
  ("s_alloc_vgpr", manual_s_ops::s_alloc_vgpr),
  ("s_atc_probe", manual_s_ops::s_atc_probe),
  ("s_atc_probe_buffer", manual_s_ops::s_atc_probe_buffer),
  ("s_barrier_signal", manual_s_ops::s_barrier_signal),
  ("s_barrier_signal_isfirst", manual_s_ops::s_barrier_signal_isfirst),
  ("s_barrier_wait", manual_s_ops::s_barrier_wait),
  ("s_buffer_load_b96", manual_s_ops::s_buffer_load_b96),
  ("s_buffer_prefetch_data", manual_s_ops::s_buffer_prefetch_data),
  ("s_cvt_f16_f32", manual_s_ops::s_cvt_f16_f32),
  ("s_cvt_hi_f32_f16", manual_s_ops::s_cvt_hi_f32_f16),
  ("s_cvt_i32_f32", manual_s_ops::s_cvt_i32_f32),
  ("s_cvt_pk_rtz_f16_f32", manual_s_ops::s_cvt_pk_rtz_f16_f32),
  ("s_cvt_u32_f32", manual_s_ops::s_cvt_u32_f32),
  ("s_fmaak_f32", manual_s_ops::s_fmaak_f32),
  ("s_fmamk_f32", manual_s_ops::s_fmamk_f32),
  ("s_load_b96", manual_s_ops::s_load_b96),
  ("s_prefetch_data", manual_s_ops::s_prefetch_data),
  ("s_prefetch_data_pc_rel", manual_s_ops::s_prefetch_data_pc_rel),
  ("s_prefetch_inst", manual_s_ops::s_prefetch_inst),
  ("s_prefetch_inst_pc_rel", manual_s_ops::s_prefetch_inst_pc_rel),
  ("s_sleep_var", manual_s_ops::s_sleep_var),
  ("s_sub_co_ci_u32", manual_s_ops::s_sub_co_ci_u32),
  ("s_sub_nc_u64", manual_s_ops::s_sub_nc_u64),
  ("s_wait_alu", manual_s_ops::s_wait_alu),
  ("s_wait_bvhcnt", manual_s_ops::s_wait_bvhcnt),
  ("s_wait_dscnt", manual_s_ops::s_wait_dscnt),
  ("s_wait_expcnt", manual_s_ops::s_wait_expcnt),
  ("s_wait_kmcnt", manual_s_ops::s_wait_kmcnt),
  ("s_wait_loadcnt", manual_s_ops::s_wait_loadcnt),
  ("s_wait_loadcnt_dscnt", manual_s_ops::s_wait_loadcnt_dscnt),
  ("s_wait_samplecnt", manual_s_ops::s_wait_samplecnt),
  ("s_wait_storecnt", manual_s_ops::s_wait_storecnt),
  ("s_wait_storecnt_dscnt", manual_s_ops::s_wait_storecnt_dscnt),
  ("v_cvt_f32_bf8", manual_v_ops::v_cvt_f32_bf8),
  ("v_cvt_f32_fp8", manual_v_ops::v_cvt_f32_fp8),
  ("v_cvt_pk_bf8_f32", manual_v_ops::v_cvt_pk_bf8_f32),
  ("v_cvt_pk_f32_bf8", manual_v_ops::v_cvt_pk_f32_bf8),
  ("v_cvt_pk_f32_fp8", manual_v_ops::v_cvt_pk_f32_fp8),
  ("v_cvt_pk_fp8_f32", manual_v_ops::v_cvt_pk_fp8_f32),
  ("v_cvt_sr_bf8_f32", manual_v_ops::v_cvt_sr_bf8_f32),
  ("v_cvt_sr_fp8_f32", manual_v_ops::v_cvt_sr_fp8_f32),
  ("v_dot4_f32_bf8_bf8", manual_v_ops::v_dot4_f32_bf8_bf8),
  ("v_dot4_f32_bf8_fp8", manual_v_ops::v_dot4_f32_bf8_fp8),
  ("v_dot4_f32_fp8_bf8", manual_v_ops::v_dot4_f32_fp8_bf8),
  ("v_dot4_f32_fp8_fp8", manual_v_ops::v_dot4_f32_fp8_fp8),
  ("v_dual_max_num_f32", manual_v_ops::v_dual_max_num_f32),
  ("v_dual_min_num_f32", manual_v_ops::v_dual_min_num_f32),
  ("v_mad_co_i64_i32", manual_v_ops::v_mad_co_i64_i32),
  ("v_mad_co_u64_u32", manual_v_ops::v_mad_co_u64_u32),
  ("v_permlane16_var_b32", manual_v_ops::v_permlane16_var_b32),
  ("v_permlanex16_var_b32", manual_v_ops::v_permlanex16_var_b32),
  ("v_pk_max_num_f16", manual_v_ops::v_pk_max_num_f16),
  ("v_pk_maximum_f16", manual_v_ops::v_pk_maximum_f16),
  ("v_pk_min_num_f16", manual_v_ops::v_pk_min_num_f16),
  ("v_pk_minimum_f16", manual_v_ops::v_pk_minimum_f16),
  ("v_swmmac_bf16_16x16x32_bf16", manual_v_ops::v_swmmac_bf16_16x16x32_bf16),
  ("v_swmmac_f16_16x16x32_f16", manual_v_ops::v_swmmac_f16_16x16x32_f16),
  ("v_swmmac_f32_16x16x32_bf8_bf8", manual_v_ops::v_swmmac_f32_16x16x32_bf8_bf8),
  ("v_swmmac_f32_16x16x32_bf8_fp8", manual_v_ops::v_swmmac_f32_16x16x32_bf8_fp8),
  ("v_swmmac_f32_16x16x32_fp8_bf8", manual_v_ops::v_swmmac_f32_16x16x32_fp8_bf8),
  ("v_swmmac_f32_16x16x32_fp8_fp8", manual_v_ops::v_swmmac_f32_16x16x32_fp8_fp8),
  ("v_swmmac_i32_16x16x32_iu4", manual_v_ops::v_swmmac_i32_16x16x32_iu4),
  ("v_swmmac_i32_16x16x32_iu8", manual_v_ops::v_swmmac_i32_16x16x32_iu8),
  ("v_swmmac_i32_16x16x64_iu4", manual_v_ops::v_swmmac_i32_16x16x64_iu4),
  ("v_wmma_f32_16x16x16_bf8_bf8", manual_v_ops::v_wmma_f32_16x16x16_bf8_bf8),
  ("v_wmma_f32_16x16x16_bf8_fp8", manual_v_ops::v_wmma_f32_16x16x16_bf8_fp8),
  ("v_wmma_f32_16x16x16_fp8_bf8", manual_v_ops::v_wmma_f32_16x16x16_fp8_bf8),
  ("v_wmma_f32_16x16x16_fp8_fp8", manual_v_ops::v_wmma_f32_16x16x16_fp8_fp8),
  ("v_wmma_i32_16x16x32_iu4", manual_v_ops::v_wmma_i32_16x16x32_iu4),
];

pub static TYPED_OPS: &[(&str, TypedHandler)] = &[
  ("buffer_atomic_pk_add_bf16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::BF16 })),
  ("buffer_atomic_pk_add_f16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F16 })),
  ("buffer_load_d16_hi_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("buffer_load_d16_hi_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("buffer_load_d16_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("buffer_load_d16_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("buffer_load_i16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I16 })),
  ("buffer_load_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("buffer_load_u16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U16 })),
  ("buffer_load_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("ds_pk_add_bf16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::BF16 })),
  ("ds_pk_add_f16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F16 })),
  ("ds_pk_add_rtn_bf16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::BF16 })),
  ("ds_pk_add_rtn_f16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F16 })),
  ("flat_atomic_pk_add_bf16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::BF16 })),
  ("flat_atomic_pk_add_f16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F16 })),
  ("global_atomic_pk_add_bf16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::BF16 })),
  ("global_atomic_pk_add_f16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F16 })),
  ("image_atomic_pk_add_bf16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::BF16 })),
  ("image_atomic_pk_add_f16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F16 })),
  ("s_add_co_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_add_co_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_add_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_add_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_buffer_load_i16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I16 })),
  ("s_buffer_load_i8", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I8 })),
  ("s_buffer_load_u16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U16 })),
  ("s_buffer_load_u8", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U8 })),
  ("s_ceil_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_ceil_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_eq_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_eq_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_ge_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_ge_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_gt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_gt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_le_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_le_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_lg_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_lg_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_lt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_lt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_neq_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_neq_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nge_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nge_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_ngt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_ngt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nle_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nle_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nlg_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nlg_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_nlt_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_nlt_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_o_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_o_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cmp_u_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cmp_u_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_cvt_f32_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_cvt_f32_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cvt_f32_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_floor_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_floor_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_fmac_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_fmac_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_load_i16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I16 })),
  ("s_load_i8", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I8 })),
  ("s_load_u16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U16 })),
  ("s_load_u8", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U8 })),
  ("s_max_num_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_max_num_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_maximum_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_maximum_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_min_num_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_min_num_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_minimum_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_minimum_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_mul_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_mul_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_mul_u64", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U64 })),
  ("s_rndne_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_rndne_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_sub_co_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_sub_co_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_sub_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_sub_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("s_trunc_f16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F16 })),
  ("s_trunc_f32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::F32 })),
  ("v_max3_num_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_max3_num_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_max_num_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_max_num_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_maximum3_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_maximum3_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_maximum_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_maximum_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_maximumminimum_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_maximumminimum_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_maxmin_num_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_maxmin_num_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_med3_num_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_med3_num_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_min3_num_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_min3_num_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_min_num_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_min_num_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_minimum3_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_minimum3_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_minimum_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_minimum_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_minimummaximum_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_minimummaximum_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_minmax_num_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_minmax_num_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_s_exp_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_s_exp_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_s_log_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_s_log_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_s_rcp_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_s_rcp_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_s_rsq_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_s_rsq_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_s_sqrt_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_s_sqrt_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_swmmac_f32_16x16x32_bf16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::BF16 })),
  ("v_swmmac_f32_16x16x32_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
];
