#!/usr/bin/env python3
from __future__ import annotations

import subprocess
from pathlib import Path

GENERATED_MARKERS = (
  "generated by",
  "@generated",
  "autogenerated",
  "auto-generated",
  "do not edit by hand",
)
GENERATED_NAMES = {
  "generated.rs",
}
SKIP_DIRS = {
  ".git",
  "__pycache__",
  "docs",
  "target",
}


def repo_root() -> Path:
  return Path(__file__).resolve().parents[1]


def list_files(root: Path) -> list[Path]:
  try:
    output = subprocess.check_output(["git", "ls-files"], cwd=root, text=True)
    files = [root / line for line in output.splitlines() if line.strip()]
    if files:
      return files
  except (OSError, subprocess.CalledProcessError):
    pass
  return [
    path
    for path in root.rglob("*")
    if path.is_file() and not any(part in SKIP_DIRS for part in path.parts)
  ]


def is_generated(path: Path) -> bool:
  if path.name in GENERATED_NAMES:
    return True
  try:
    head = path.read_bytes()[:4096]
  except OSError:
    return True
  return any(marker in head.decode("utf-8", errors="ignore").lower() for marker in GENERATED_MARKERS)


def count_lines(path: Path) -> int:
  data = path.read_bytes()
  if not data:
    return 0
  return data.count(b"\n") + (0 if data.endswith(b"\n") else 1)


def main() -> None:
  root = repo_root()
  files = list_files(root)
  rows = []
  skipped = 0
  for path in files:
    if is_generated(path):
      skipped += 1
      continue
    try:
      lines = count_lines(path)
    except OSError:
      skipped += 1
      continue
    rows.append((lines, path))
  rows.sort(key=lambda item: (-item[0], str(item[1])))
  if not rows:
    print("no files to report")
    return

  line_width = max(len("lines"), max(len(str(lines)) for lines, _ in rows))
  file_width = max(len("file"), max(len(str(path.relative_to(root))) for _, path in rows))
  print(f"{'lines'.rjust(line_width)}  {'file'.ljust(file_width)}")
  print(f"{'-' * line_width}  {'-' * file_width}")
  for lines, path in rows:
    rel_path = path.relative_to(root)
    print(f"{str(lines).rjust(line_width)}  {str(rel_path).ljust(file_width)}")
  total = sum(lines for lines, _ in rows)
  print(f"{total} lines in {len(rows)} files (skipped {skipped} autogenerated)")


if __name__ == "__main__":
  main()
