use crate::sim::Handler;
use crate::ops::typed::TypedHandler;
use crate::isa::types::DataType;
use crate::ops::typed_mem_ops::TypedMemHandler;
use crate::ops::typed_s_ops::TypedSHandler;
use crate::ops::typed_v_ops::TypedVHandler;
use crate::ops::typed_v_ops::BinaryOp;
use crate::ops::typed_v_ops::CmpOp;

pub mod manual_v_ops;
pub mod manual_s_ops;
pub mod manual_mem_ops;
pub mod manual_misc_ops;

pub static OPS: &[(&str, Handler)] = &[
  ("buffer_atomic_and_b32", manual_mem_ops::buffer_atomic_and_b32),
  ("buffer_atomic_and_b64", manual_mem_ops::buffer_atomic_and_b64),
  ("buffer_atomic_cmpswap_b32", manual_mem_ops::buffer_atomic_cmpswap_b32),
  ("buffer_atomic_cmpswap_b64", manual_mem_ops::buffer_atomic_cmpswap_b64),
  ("buffer_atomic_or_b32", manual_mem_ops::buffer_atomic_or_b32),
  ("buffer_atomic_or_b64", manual_mem_ops::buffer_atomic_or_b64),
  ("buffer_atomic_swap_b32", manual_mem_ops::buffer_atomic_swap_b32),
  ("buffer_atomic_swap_b64", manual_mem_ops::buffer_atomic_swap_b64),
  ("buffer_atomic_xor_b32", manual_mem_ops::buffer_atomic_xor_b32),
  ("buffer_atomic_xor_b64", manual_mem_ops::buffer_atomic_xor_b64),
  ("buffer_load_d16_format_x", manual_mem_ops::buffer_load_d16_format_x),
  ("buffer_load_d16_format_xy", manual_mem_ops::buffer_load_d16_format_xy),
  ("buffer_load_d16_format_xyz", manual_mem_ops::buffer_load_d16_format_xyz),
  ("buffer_load_d16_format_xyzw", manual_mem_ops::buffer_load_d16_format_xyzw),
  ("buffer_load_d16_hi_format_x", manual_mem_ops::buffer_load_d16_hi_format_x),
  ("buffer_load_format_x", manual_mem_ops::buffer_load_format_x),
  ("buffer_load_format_xy", manual_mem_ops::buffer_load_format_xy),
  ("buffer_load_format_xyz", manual_mem_ops::buffer_load_format_xyz),
  ("buffer_load_format_xyzw", manual_mem_ops::buffer_load_format_xyzw),
  ("buffer_store_d16_format_x", manual_mem_ops::buffer_store_d16_format_x),
  ("buffer_store_d16_format_xy", manual_mem_ops::buffer_store_d16_format_xy),
  ("buffer_store_d16_format_xyz", manual_mem_ops::buffer_store_d16_format_xyz),
  ("buffer_store_d16_format_xyzw", manual_mem_ops::buffer_store_d16_format_xyzw),
  ("buffer_store_d16_hi_format_x", manual_mem_ops::buffer_store_d16_hi_format_x),
  ("buffer_store_format_x", manual_mem_ops::buffer_store_format_x),
  ("buffer_store_format_xy", manual_mem_ops::buffer_store_format_xy),
  ("buffer_store_format_xyz", manual_mem_ops::buffer_store_format_xyz),
  ("buffer_store_format_xyzw", manual_mem_ops::buffer_store_format_xyzw),
  ("ds_and_b32", manual_mem_ops::ds_and_b32),
  ("ds_and_b64", manual_mem_ops::ds_and_b64),
  ("ds_and_rtn_b32", manual_mem_ops::ds_and_rtn_b32),
  ("ds_and_rtn_b64", manual_mem_ops::ds_and_rtn_b64),
  ("ds_append", manual_mem_ops::ds_append),
  ("ds_bpermute_b32", manual_mem_ops::ds_bpermute_b32),
  ("ds_cmpstore_b32", manual_mem_ops::ds_cmpstore_b32),
  ("ds_cmpstore_b64", manual_mem_ops::ds_cmpstore_b64),
  ("ds_cmpstore_rtn_b32", manual_mem_ops::ds_cmpstore_rtn_b32),
  ("ds_cmpstore_rtn_b64", manual_mem_ops::ds_cmpstore_rtn_b64),
  ("ds_condxchg32_rtn_b64", manual_mem_ops::ds_condxchg32_rtn_b64),
  ("ds_consume", manual_mem_ops::ds_consume),
  ("ds_load_2addr_b32", manual_mem_ops::ds_load_2addr_b32),
  ("ds_load_2addr_b64", manual_mem_ops::ds_load_2addr_b64),
  ("ds_load_2addr_stride64_b32", manual_mem_ops::ds_load_2addr_stride64_b32),
  ("ds_load_2addr_stride64_b64", manual_mem_ops::ds_load_2addr_stride64_b64),
  ("ds_load_addtid_b32", manual_mem_ops::ds_load_addtid_b32),
  ("ds_load_b128", manual_mem_ops::ds_load_b128),
  ("ds_load_b32", manual_mem_ops::ds_load_b32),
  ("ds_load_b64", manual_mem_ops::ds_load_b64),
  ("ds_load_b96", manual_mem_ops::ds_load_b96),
  ("ds_load_i8_d16", manual_mem_ops::ds_load_i8_d16),
  ("ds_load_i8_d16_hi", manual_mem_ops::ds_load_i8_d16_hi),
  ("ds_load_u16_d16", manual_mem_ops::ds_load_u16_d16),
  ("ds_load_u16_d16_hi", manual_mem_ops::ds_load_u16_d16_hi),
  ("ds_load_u8_d16", manual_mem_ops::ds_load_u8_d16),
  ("ds_load_u8_d16_hi", manual_mem_ops::ds_load_u8_d16_hi),
  ("ds_mskor_b32", manual_mem_ops::ds_mskor_b32),
  ("ds_mskor_b64", manual_mem_ops::ds_mskor_b64),
  ("ds_mskor_rtn_b32", manual_mem_ops::ds_mskor_rtn_b32),
  ("ds_mskor_rtn_b64", manual_mem_ops::ds_mskor_rtn_b64),
  ("ds_nop", manual_mem_ops::ds_nop),
  ("ds_or_b32", manual_mem_ops::ds_or_b32),
  ("ds_or_b64", manual_mem_ops::ds_or_b64),
  ("ds_or_rtn_b32", manual_mem_ops::ds_or_rtn_b32),
  ("ds_or_rtn_b64", manual_mem_ops::ds_or_rtn_b64),
  ("ds_permute_b32", manual_mem_ops::ds_permute_b32),
  ("ds_store_2addr_b32", manual_mem_ops::ds_store_2addr_b32),
  ("ds_store_2addr_b64", manual_mem_ops::ds_store_2addr_b64),
  ("ds_store_2addr_stride64_b32", manual_mem_ops::ds_store_2addr_stride64_b32),
  ("ds_store_2addr_stride64_b64", manual_mem_ops::ds_store_2addr_stride64_b64),
  ("ds_store_addtid_b32", manual_mem_ops::ds_store_addtid_b32),
  ("ds_store_b128", manual_mem_ops::ds_store_b128),
  ("ds_store_b16", manual_mem_ops::ds_store_b16),
  ("ds_store_b16_d16_hi", manual_mem_ops::ds_store_b16_d16_hi),
  ("ds_store_b32", manual_mem_ops::ds_store_b32),
  ("ds_store_b64", manual_mem_ops::ds_store_b64),
  ("ds_store_b8", manual_mem_ops::ds_store_b8),
  ("ds_store_b8_d16_hi", manual_mem_ops::ds_store_b8_d16_hi),
  ("ds_store_b96", manual_mem_ops::ds_store_b96),
  ("ds_storexchg_2addr_rtn_b32", manual_mem_ops::ds_storexchg_2addr_rtn_b32),
  ("ds_storexchg_2addr_rtn_b64", manual_mem_ops::ds_storexchg_2addr_rtn_b64),
  ("ds_storexchg_2addr_stride64_rtn_b32", manual_mem_ops::ds_storexchg_2addr_stride64_rtn_b32),
  ("ds_storexchg_2addr_stride64_rtn_b64", manual_mem_ops::ds_storexchg_2addr_stride64_rtn_b64),
  ("ds_storexchg_rtn_b32", manual_mem_ops::ds_storexchg_rtn_b32),
  ("ds_storexchg_rtn_b64", manual_mem_ops::ds_storexchg_rtn_b64),
  ("ds_swizzle_b32", manual_mem_ops::ds_swizzle_b32),
  ("ds_xor_b32", manual_mem_ops::ds_xor_b32),
  ("ds_xor_b64", manual_mem_ops::ds_xor_b64),
  ("ds_xor_rtn_b32", manual_mem_ops::ds_xor_rtn_b32),
  ("ds_xor_rtn_b64", manual_mem_ops::ds_xor_rtn_b64),
  ("flat_atomic_and_b32", manual_mem_ops::flat_atomic_and_b32),
  ("flat_atomic_and_b64", manual_mem_ops::flat_atomic_and_b64),
  ("flat_atomic_cmpswap_b32", manual_mem_ops::flat_atomic_cmpswap_b32),
  ("flat_atomic_cmpswap_b64", manual_mem_ops::flat_atomic_cmpswap_b64),
  ("flat_atomic_or_b32", manual_mem_ops::flat_atomic_or_b32),
  ("flat_atomic_or_b64", manual_mem_ops::flat_atomic_or_b64),
  ("flat_atomic_swap_b32", manual_mem_ops::flat_atomic_swap_b32),
  ("flat_atomic_swap_b64", manual_mem_ops::flat_atomic_swap_b64),
  ("flat_atomic_xor_b32", manual_mem_ops::flat_atomic_xor_b32),
  ("flat_atomic_xor_b64", manual_mem_ops::flat_atomic_xor_b64),
  ("flat_load_b128", manual_mem_ops::flat_load_b128),
  ("flat_load_b32", manual_mem_ops::flat_load_b32),
  ("flat_load_b64", manual_mem_ops::flat_load_b64),
  ("flat_load_b96", manual_mem_ops::flat_load_b96),
  ("flat_load_d16_b16", manual_mem_ops::flat_load_d16_b16),
  ("flat_load_d16_hi_b16", manual_mem_ops::flat_load_d16_hi_b16),
  ("flat_store_b128", manual_mem_ops::flat_store_b128),
  ("flat_store_b16", manual_mem_ops::flat_store_b16),
  ("flat_store_b32", manual_mem_ops::flat_store_b32),
  ("flat_store_b64", manual_mem_ops::flat_store_b64),
  ("flat_store_b8", manual_mem_ops::flat_store_b8),
  ("flat_store_b96", manual_mem_ops::flat_store_b96),
  ("flat_store_d16_hi_b16", manual_mem_ops::flat_store_d16_hi_b16),
  ("flat_store_d16_hi_b8", manual_mem_ops::flat_store_d16_hi_b8),
  ("global_atomic_and_b32", manual_mem_ops::global_atomic_and_b32),
  ("global_atomic_and_b64", manual_mem_ops::global_atomic_and_b64),
  ("global_atomic_cmpswap_b32", manual_mem_ops::global_atomic_cmpswap_b32),
  ("global_atomic_cmpswap_b64", manual_mem_ops::global_atomic_cmpswap_b64),
  ("global_atomic_or_b32", manual_mem_ops::global_atomic_or_b32),
  ("global_atomic_or_b64", manual_mem_ops::global_atomic_or_b64),
  ("global_atomic_swap_b32", manual_mem_ops::global_atomic_swap_b32),
  ("global_atomic_swap_b64", manual_mem_ops::global_atomic_swap_b64),
  ("global_atomic_xor_b32", manual_mem_ops::global_atomic_xor_b32),
  ("global_atomic_xor_b64", manual_mem_ops::global_atomic_xor_b64),
  ("image_atomic_and", manual_mem_ops::image_atomic_and),
  ("image_atomic_cmpswap", manual_mem_ops::image_atomic_cmpswap),
  ("image_atomic_or", manual_mem_ops::image_atomic_or),
  ("image_atomic_swap", manual_mem_ops::image_atomic_swap),
  ("image_atomic_xor", manual_mem_ops::image_atomic_xor),
  ("s_abs_i32", manual_s_ops::s_abs_i32),
  ("s_absdiff_i32", manual_s_ops::s_absdiff_i32),
  ("s_and_b32", manual_s_ops::s_and_b32),
  ("s_and_b64", manual_s_ops::s_and_b64),
  ("s_and_not0_saveexec_b32", manual_s_ops::s_and_not0_saveexec_b32),
  ("s_and_not0_saveexec_b64", manual_s_ops::s_and_not0_saveexec_b64),
  ("s_and_not0_wrexec_b32", manual_s_ops::s_and_not0_wrexec_b32),
  ("s_and_not0_wrexec_b64", manual_s_ops::s_and_not0_wrexec_b64),
  ("s_and_not1_b32", manual_s_ops::s_and_not1_b32),
  ("s_and_not1_b64", manual_s_ops::s_and_not1_b64),
  ("s_and_not1_saveexec_b32", manual_s_ops::s_and_not1_saveexec_b32),
  ("s_and_not1_saveexec_b64", manual_s_ops::s_and_not1_saveexec_b64),
  ("s_and_not1_wrexec_b32", manual_s_ops::s_and_not1_wrexec_b32),
  ("s_and_not1_wrexec_b64", manual_s_ops::s_and_not1_wrexec_b64),
  ("s_and_saveexec_b32", manual_s_ops::s_and_saveexec_b32),
  ("s_and_saveexec_b64", manual_s_ops::s_and_saveexec_b64),
  ("s_bcnt0_i32_b32", manual_s_ops::s_bcnt0_i32_b32),
  ("s_bcnt0_i32_b64", manual_s_ops::s_bcnt0_i32_b64),
  ("s_bcnt1_i32_b32", manual_s_ops::s_bcnt1_i32_b32),
  ("s_bcnt1_i32_b64", manual_s_ops::s_bcnt1_i32_b64),
  ("s_bfm_b32", manual_s_ops::s_bfm_b32),
  ("s_bfm_b64", manual_s_ops::s_bfm_b64),
  ("s_bitcmp0_b32", manual_s_ops::s_bitcmp0_b32),
  ("s_bitcmp0_b64", manual_s_ops::s_bitcmp0_b64),
  ("s_bitcmp1_b32", manual_s_ops::s_bitcmp1_b32),
  ("s_bitcmp1_b64", manual_s_ops::s_bitcmp1_b64),
  ("s_bitreplicate_b64_b32", manual_s_ops::s_bitreplicate_b64_b32),
  ("s_bitset0_b32", manual_s_ops::s_bitset0_b32),
  ("s_bitset0_b64", manual_s_ops::s_bitset0_b64),
  ("s_bitset1_b32", manual_s_ops::s_bitset1_b32),
  ("s_bitset1_b64", manual_s_ops::s_bitset1_b64),
  ("s_branch", manual_s_ops::s_branch),
  ("s_brev_b32", manual_s_ops::s_brev_b32),
  ("s_brev_b64", manual_s_ops::s_brev_b64),
  ("s_buffer_load_b128", manual_s_ops::s_buffer_load_b128),
  ("s_buffer_load_b256", manual_s_ops::s_buffer_load_b256),
  ("s_buffer_load_b32", manual_s_ops::s_buffer_load_b32),
  ("s_buffer_load_b512", manual_s_ops::s_buffer_load_b512),
  ("s_buffer_load_b64", manual_s_ops::s_buffer_load_b64),
  ("s_call_b64", manual_s_ops::s_call_b64),
  ("s_cbranch_execnz", manual_s_ops::s_cbranch_execnz),
  ("s_cbranch_execz", manual_s_ops::s_cbranch_execz),
  ("s_cbranch_scc0", manual_s_ops::s_cbranch_scc0),
  ("s_cbranch_scc1", manual_s_ops::s_cbranch_scc1),
  ("s_cbranch_vccnz", manual_s_ops::s_cbranch_vccnz),
  ("s_cbranch_vccz", manual_s_ops::s_cbranch_vccz),
  ("s_clause", manual_s_ops::s_clause),
  ("s_cls_i32", manual_s_ops::s_cls_i32),
  ("s_cls_i32_i64", manual_s_ops::s_cls_i32_i64),
  ("s_cmov_b32", manual_s_ops::s_cmov_b32),
  ("s_cmov_b64", manual_s_ops::s_cmov_b64),
  ("s_cmovk_i32", manual_s_ops::s_cmovk_i32),
  ("s_code_end", manual_s_ops::s_code_end),
  ("s_cselect_b32", manual_s_ops::s_cselect_b32),
  ("s_cselect_b64", manual_s_ops::s_cselect_b64),
  ("s_ctz_i32_b32", manual_s_ops::s_ctz_i32_b32),
  ("s_ctz_i32_b64", manual_s_ops::s_ctz_i32_b64),
  ("s_dcache_inv", manual_s_ops::s_dcache_inv),
  ("s_decperflevel", manual_s_ops::s_decperflevel),
  ("s_delay_alu", manual_s_ops::s_delay_alu),
  ("s_denorm_mode", manual_s_ops::s_denorm_mode),
  ("s_endpgm", manual_s_ops::s_endpgm),
  ("s_endpgm_saved", manual_s_ops::s_endpgm_saved),
  ("s_getpc_b64", manual_s_ops::s_getpc_b64),
  ("s_getreg_b32", manual_s_ops::s_getreg_b32),
  ("s_icache_inv", manual_s_ops::s_icache_inv),
  ("s_incperflevel", manual_s_ops::s_incperflevel),
  ("s_load_b128", manual_s_ops::s_load_b128),
  ("s_load_b256", manual_s_ops::s_load_b256),
  ("s_load_b32", manual_s_ops::s_load_b32),
  ("s_load_b512", manual_s_ops::s_load_b512),
  ("s_load_b64", manual_s_ops::s_load_b64),
  ("s_lshl1_add_u32", manual_s_ops::s_lshl1_add_u32),
  ("s_lshl2_add_u32", manual_s_ops::s_lshl2_add_u32),
  ("s_lshl3_add_u32", manual_s_ops::s_lshl3_add_u32),
  ("s_lshl4_add_u32", manual_s_ops::s_lshl4_add_u32),
  ("s_lshl_b32", manual_s_ops::s_lshl_b32),
  ("s_lshl_b64", manual_s_ops::s_lshl_b64),
  ("s_lshr_b32", manual_s_ops::s_lshr_b32),
  ("s_lshr_b64", manual_s_ops::s_lshr_b64),
  ("s_mov_b32", manual_s_ops::s_mov_b32),
  ("s_mov_b64", manual_s_ops::s_mov_b64),
  ("s_movk_i32", manual_s_ops::s_movk_i32),
  ("s_movreld_b32", manual_s_ops::s_movreld_b32),
  ("s_movreld_b64", manual_s_ops::s_movreld_b64),
  ("s_movrels_b32", manual_s_ops::s_movrels_b32),
  ("s_movrels_b64", manual_s_ops::s_movrels_b64),
  ("s_movrelsd_2_b32", manual_s_ops::s_movrelsd_2_b32),
  ("s_mulk_i32", manual_s_ops::s_mulk_i32),
  ("s_nand_b32", manual_s_ops::s_nand_b32),
  ("s_nand_b64", manual_s_ops::s_nand_b64),
  ("s_nand_saveexec_b32", manual_s_ops::s_nand_saveexec_b32),
  ("s_nand_saveexec_b64", manual_s_ops::s_nand_saveexec_b64),
  ("s_nop", manual_s_ops::s_nop),
  ("s_nor_b32", manual_s_ops::s_nor_b32),
  ("s_nor_b64", manual_s_ops::s_nor_b64),
  ("s_nor_saveexec_b32", manual_s_ops::s_nor_saveexec_b32),
  ("s_nor_saveexec_b64", manual_s_ops::s_nor_saveexec_b64),
  ("s_not_b32", manual_s_ops::s_not_b32),
  ("s_not_b64", manual_s_ops::s_not_b64),
  ("s_or_b32", manual_s_ops::s_or_b32),
  ("s_or_b64", manual_s_ops::s_or_b64),
  ("s_or_not0_saveexec_b32", manual_s_ops::s_or_not0_saveexec_b32),
  ("s_or_not0_saveexec_b64", manual_s_ops::s_or_not0_saveexec_b64),
  ("s_or_not1_b32", manual_s_ops::s_or_not1_b32),
  ("s_or_not1_b64", manual_s_ops::s_or_not1_b64),
  ("s_or_not1_saveexec_b32", manual_s_ops::s_or_not1_saveexec_b32),
  ("s_or_not1_saveexec_b64", manual_s_ops::s_or_not1_saveexec_b64),
  ("s_or_saveexec_b32", manual_s_ops::s_or_saveexec_b32),
  ("s_or_saveexec_b64", manual_s_ops::s_or_saveexec_b64),
  ("s_pack_hh_b32_b16", manual_s_ops::s_pack_hh_b32_b16),
  ("s_pack_hl_b32_b16", manual_s_ops::s_pack_hl_b32_b16),
  ("s_pack_lh_b32_b16", manual_s_ops::s_pack_lh_b32_b16),
  ("s_pack_ll_b32_b16", manual_s_ops::s_pack_ll_b32_b16),
  ("s_quadmask_b32", manual_s_ops::s_quadmask_b32),
  ("s_quadmask_b64", manual_s_ops::s_quadmask_b64),
  ("s_rfe_b64", manual_s_ops::s_rfe_b64),
  ("s_round_mode", manual_s_ops::s_round_mode),
  ("s_sendmsg", manual_s_ops::s_sendmsg),
  ("s_sendmsg_rtn_b32", manual_s_ops::s_sendmsg_rtn_b32),
  ("s_sendmsg_rtn_b64", manual_s_ops::s_sendmsg_rtn_b64),
  ("s_sendmsghalt", manual_s_ops::s_sendmsghalt),
  ("s_sethalt", manual_s_ops::s_sethalt),
  ("s_setkill", manual_s_ops::s_setkill),
  ("s_setpc_b64", manual_s_ops::s_setpc_b64),
  ("s_setprio", manual_s_ops::s_setprio),
  ("s_setreg_b32", manual_s_ops::s_setreg_b32),
  ("s_setreg_imm32_b32", manual_s_ops::s_setreg_imm32_b32),
  ("s_sleep", manual_s_ops::s_sleep),
  ("s_swappc_b64", manual_s_ops::s_swappc_b64),
  ("s_trap", manual_s_ops::s_trap),
  ("s_ttracedata", manual_s_ops::s_ttracedata),
  ("s_ttracedata_imm", manual_s_ops::s_ttracedata_imm),
  ("s_version", manual_s_ops::s_version),
  ("s_wait_event", manual_s_ops::s_wait_event),
  ("s_wait_idle", manual_s_ops::s_wait_idle),
  ("s_wakeup", manual_s_ops::s_wakeup),
  ("s_wqm_b32", manual_s_ops::s_wqm_b32),
  ("s_wqm_b64", manual_s_ops::s_wqm_b64),
  ("s_xnor_b32", manual_s_ops::s_xnor_b32),
  ("s_xnor_b64", manual_s_ops::s_xnor_b64),
  ("s_xnor_saveexec_b32", manual_s_ops::s_xnor_saveexec_b32),
  ("s_xnor_saveexec_b64", manual_s_ops::s_xnor_saveexec_b64),
  ("s_xor_b32", manual_s_ops::s_xor_b32),
  ("s_xor_b64", manual_s_ops::s_xor_b64),
  ("s_xor_saveexec_b32", manual_s_ops::s_xor_saveexec_b32),
  ("s_xor_saveexec_b64", manual_s_ops::s_xor_saveexec_b64),
  ("tbuffer_load_d16_format_x", manual_misc_ops::tbuffer_load_d16_format_x),
  ("tbuffer_load_d16_format_xy", manual_misc_ops::tbuffer_load_d16_format_xy),
  ("tbuffer_load_d16_format_xyz", manual_misc_ops::tbuffer_load_d16_format_xyz),
  ("tbuffer_load_d16_format_xyzw", manual_misc_ops::tbuffer_load_d16_format_xyzw),
  ("tbuffer_load_format_x", manual_misc_ops::tbuffer_load_format_x),
  ("tbuffer_load_format_xy", manual_misc_ops::tbuffer_load_format_xy),
  ("tbuffer_load_format_xyz", manual_misc_ops::tbuffer_load_format_xyz),
  ("tbuffer_load_format_xyzw", manual_misc_ops::tbuffer_load_format_xyzw),
  ("tbuffer_store_d16_format_x", manual_misc_ops::tbuffer_store_d16_format_x),
  ("tbuffer_store_d16_format_xy", manual_misc_ops::tbuffer_store_d16_format_xy),
  ("tbuffer_store_d16_format_xyz", manual_misc_ops::tbuffer_store_d16_format_xyz),
  ("tbuffer_store_d16_format_xyzw", manual_misc_ops::tbuffer_store_d16_format_xyzw),
  ("tbuffer_store_format_x", manual_misc_ops::tbuffer_store_format_x),
  ("tbuffer_store_format_xy", manual_misc_ops::tbuffer_store_format_xy),
  ("tbuffer_store_format_xyz", manual_misc_ops::tbuffer_store_format_xyz),
  ("tbuffer_store_format_xyzw", manual_misc_ops::tbuffer_store_format_xyzw),
  ("v_add3_u32", manual_v_ops::v_add3_u32),
  ("v_add_co_ci_u32", manual_v_ops::v_add_co_ci_u32),
  ("v_add_co_u32", manual_v_ops::v_add_co_u32),
  ("v_add_lshl_u32", manual_v_ops::v_add_lshl_u32),
  ("v_alignbit_b32", manual_v_ops::v_alignbit_b32),
  ("v_alignbyte_b32", manual_v_ops::v_alignbyte_b32),
  ("v_and_b16", manual_v_ops::v_and_b16),
  ("v_and_b32", manual_v_ops::v_and_b32),
  ("v_and_or_b32", manual_v_ops::v_and_or_b32),
  ("v_bcnt_u32_b32", manual_v_ops::v_bcnt_u32_b32),
  ("v_bfi_b32", manual_v_ops::v_bfi_b32),
  ("v_bfm_b32", manual_v_ops::v_bfm_b32),
  ("v_bfrev_b32", manual_v_ops::v_bfrev_b32),
  ("v_cls_i32", manual_v_ops::v_cls_i32),
  ("v_clz_i32_u32", manual_v_ops::v_clz_i32_u32),
  ("v_cndmask_b16", manual_v_ops::v_cndmask_b16),
  ("v_cndmask_b32", manual_v_ops::v_cndmask_b32),
  ("v_ctz_i32_b32", manual_v_ops::v_ctz_i32_b32),
  ("v_cubeid_f32", manual_v_ops::v_cubeid_f32),
  ("v_cubema_f32", manual_v_ops::v_cubema_f32),
  ("v_cubesc_f32", manual_v_ops::v_cubesc_f32),
  ("v_cubetc_f32", manual_v_ops::v_cubetc_f32),
  ("v_cvt_f32_ubyte0", manual_v_ops::v_cvt_f32_ubyte0),
  ("v_cvt_f32_ubyte1", manual_v_ops::v_cvt_f32_ubyte1),
  ("v_cvt_f32_ubyte2", manual_v_ops::v_cvt_f32_ubyte2),
  ("v_cvt_f32_ubyte3", manual_v_ops::v_cvt_f32_ubyte3),
  ("v_cvt_floor_i32_f32", manual_v_ops::v_cvt_floor_i32_f32),
  ("v_cvt_i16_f16", manual_v_ops::v_cvt_i16_f16),
  ("v_cvt_nearest_i32_f32", manual_v_ops::v_cvt_nearest_i32_f32),
  ("v_cvt_norm_i16_f16", manual_v_ops::v_cvt_norm_i16_f16),
  ("v_cvt_norm_u16_f16", manual_v_ops::v_cvt_norm_u16_f16),
  ("v_cvt_off_f32_i4", manual_v_ops::v_cvt_off_f32_i4),
  ("v_cvt_pk_rtz_f16_f32", manual_v_ops::v_cvt_pk_rtz_f16_f32),
  ("v_cvt_pk_u8_f32", manual_v_ops::v_cvt_pk_u8_f32),
  ("v_cvt_u16_f16", manual_v_ops::v_cvt_u16_f16),
  ("v_div_fmas_f32", manual_v_ops::v_div_fmas_f32),
  ("v_div_scale_f32", manual_v_ops::v_div_scale_f32),
  ("v_dot2_bf16_bf16", manual_v_ops::v_dot2_bf16_bf16),
  ("v_dot2_f16_f16", manual_v_ops::v_dot2_f16_f16),
  ("v_dot4_i32_iu8", manual_v_ops::v_dot4_i32_iu8),
  ("v_dot4_u32_u8", manual_v_ops::v_dot4_u32_u8),
  ("v_dot8_i32_iu4", manual_v_ops::v_dot8_i32_iu4),
  ("v_dot8_u32_u4", manual_v_ops::v_dot8_u32_u4),
  ("v_dual_add_f32", manual_v_ops::v_dual_add_f32),
  ("v_dual_add_nc_u32", manual_v_ops::v_dual_add_nc_u32),
  ("v_dual_and_b32", manual_v_ops::v_dual_and_b32),
  ("v_dual_cndmask_b32", manual_v_ops::v_dual_cndmask_b32),
  ("v_dual_fmaak_f32", manual_v_ops::v_dual_fmaak_f32),
  ("v_dual_fmac_f32", manual_v_ops::v_dual_fmac_f32),
  ("v_dual_fmamk_f32", manual_v_ops::v_dual_fmamk_f32),
  ("v_dual_lshlrev_b32", manual_v_ops::v_dual_lshlrev_b32),
  ("v_dual_mov_b32", manual_v_ops::v_dual_mov_b32),
  ("v_dual_mul_dx9_zero_f32", manual_v_ops::v_dual_mul_dx9_zero_f32),
  ("v_dual_mul_f32", manual_v_ops::v_dual_mul_f32),
  ("v_dual_sub_f32", manual_v_ops::v_dual_sub_f32),
  ("v_dual_subrev_f32", manual_v_ops::v_dual_subrev_f32),
  ("v_fma_dx9_zero_f32", manual_v_ops::v_fma_dx9_zero_f32),
  ("v_fma_mix_f32", manual_v_ops::v_fma_mix_f32),
  ("v_fma_mixhi_f16", manual_v_ops::v_fma_mixhi_f16),
  ("v_fma_mixlo_f16", manual_v_ops::v_fma_mixlo_f16),
  ("v_frexp_exp_i16_f16", manual_v_ops::v_frexp_exp_i16_f16),
  ("v_frexp_exp_i32_f32", manual_v_ops::v_frexp_exp_i32_f32),
  ("v_interp_p10_f16_f32", manual_v_ops::v_interp_p10_f16_f32),
  ("v_interp_p10_f32", manual_v_ops::v_interp_p10_f32),
  ("v_interp_p10_rtz_f16_f32", manual_v_ops::v_interp_p10_rtz_f16_f32),
  ("v_interp_p2_f16_f32", manual_v_ops::v_interp_p2_f16_f32),
  ("v_interp_p2_f32", manual_v_ops::v_interp_p2_f32),
  ("v_interp_p2_rtz_f16_f32", manual_v_ops::v_interp_p2_rtz_f16_f32),
  ("v_lerp_u8", manual_v_ops::v_lerp_u8),
  ("v_lshl_add_u32", manual_v_ops::v_lshl_add_u32),
  ("v_lshl_or_b32", manual_v_ops::v_lshl_or_b32),
  ("v_lshlrev_b16", manual_v_ops::v_lshlrev_b16),
  ("v_lshlrev_b32", manual_v_ops::v_lshlrev_b32),
  ("v_lshlrev_b64", manual_v_ops::v_lshlrev_b64),
  ("v_lshrrev_b16", manual_v_ops::v_lshrrev_b16),
  ("v_lshrrev_b32", manual_v_ops::v_lshrrev_b32),
  ("v_lshrrev_b64", manual_v_ops::v_lshrrev_b64),
  ("v_mad_i32_i16", manual_v_ops::v_mad_i32_i16),
  ("v_mad_i32_i24", manual_v_ops::v_mad_i32_i24),
  ("v_mad_u32_u16", manual_v_ops::v_mad_u32_u16),
  ("v_mad_u32_u24", manual_v_ops::v_mad_u32_u24),
  ("v_mbcnt_hi_u32_b32", manual_v_ops::v_mbcnt_hi_u32_b32),
  ("v_mbcnt_lo_u32_b32", manual_v_ops::v_mbcnt_lo_u32_b32),
  ("v_mov_b16", manual_v_ops::v_mov_b16),
  ("v_mov_b32", manual_v_ops::v_mov_b32),
  ("v_movreld_b32", manual_v_ops::v_movreld_b32),
  ("v_movrels_b32", manual_v_ops::v_movrels_b32),
  ("v_movrelsd_2_b32", manual_v_ops::v_movrelsd_2_b32),
  ("v_movrelsd_b32", manual_v_ops::v_movrelsd_b32),
  ("v_mqsad_pk_u16_u8", manual_v_ops::v_mqsad_pk_u16_u8),
  ("v_mqsad_u32_u8", manual_v_ops::v_mqsad_u32_u8),
  ("v_msad_u8", manual_v_ops::v_msad_u8),
  ("v_mul_dx9_zero_f32", manual_v_ops::v_mul_dx9_zero_f32),
  ("v_mul_hi_i32_i24", manual_v_ops::v_mul_hi_i32_i24),
  ("v_mul_hi_u32_u24", manual_v_ops::v_mul_hi_u32_u24),
  ("v_mul_i32_i24", manual_v_ops::v_mul_i32_i24),
  ("v_mul_u32_u24", manual_v_ops::v_mul_u32_u24),
  ("v_mullit_f32", manual_v_ops::v_mullit_f32),
  ("v_nop", manual_v_ops::v_nop),
  ("v_not_b16", manual_v_ops::v_not_b16),
  ("v_not_b32", manual_v_ops::v_not_b32),
  ("v_or3_b32", manual_v_ops::v_or3_b32),
  ("v_or_b16", manual_v_ops::v_or_b16),
  ("v_or_b32", manual_v_ops::v_or_b32),
  ("v_pack_b32_f16", manual_v_ops::v_pack_b32_f16),
  ("v_perm_b32", manual_v_ops::v_perm_b32),
  ("v_permlane16_b32", manual_v_ops::v_permlane16_b32),
  ("v_permlane64_b32", manual_v_ops::v_permlane64_b32),
  ("v_permlanex16_b32", manual_v_ops::v_permlanex16_b32),
  ("v_pipeflush", manual_v_ops::v_pipeflush),
  ("v_pk_ashrrev_i16", manual_v_ops::v_pk_ashrrev_i16),
  ("v_pk_fma_f16", manual_v_ops::v_pk_fma_f16),
  ("v_pk_fmac_f16", manual_v_ops::v_pk_fmac_f16),
  ("v_pk_lshlrev_b16", manual_v_ops::v_pk_lshlrev_b16),
  ("v_pk_lshrrev_b16", manual_v_ops::v_pk_lshrrev_b16),
  ("v_pk_mul_f16", manual_v_ops::v_pk_mul_f16),
  ("v_pk_mul_lo_u16", manual_v_ops::v_pk_mul_lo_u16),
  ("v_qsad_pk_u16_u8", manual_v_ops::v_qsad_pk_u16_u8),
  ("v_rcp_iflag_f32", manual_v_ops::v_rcp_iflag_f32),
  ("v_readfirstlane_b32", manual_v_ops::v_readfirstlane_b32),
  ("v_readlane_b32", manual_v_ops::v_readlane_b32),
  ("v_sad_hi_u8", manual_v_ops::v_sad_hi_u8),
  ("v_sat_pk_u8_i16", manual_v_ops::v_sat_pk_u8_i16),
  ("v_sub_co_ci_u32", manual_v_ops::v_sub_co_ci_u32),
  ("v_sub_co_u32", manual_v_ops::v_sub_co_u32),
  ("v_subrev_co_ci_u32", manual_v_ops::v_subrev_co_ci_u32),
  ("v_subrev_co_u32", manual_v_ops::v_subrev_co_u32),
  ("v_subrev_nc_u32", manual_v_ops::v_subrev_nc_u32),
  ("v_swap_b16", manual_v_ops::v_swap_b16),
  ("v_swap_b32", manual_v_ops::v_swap_b32),
  ("v_swaprel_b32", manual_v_ops::v_swaprel_b32),
  ("v_wmma_bf16_16x16x16_bf16", manual_v_ops::v_wmma_bf16_16x16x16_bf16),
  ("v_wmma_f16_16x16x16_f16", manual_v_ops::v_wmma_f16_16x16x16_f16),
  ("v_wmma_i32_16x16x16_iu4", manual_v_ops::v_wmma_i32_16x16x16_iu4),
  ("v_wmma_i32_16x16x16_iu8", manual_v_ops::v_wmma_i32_16x16x16_iu8),
  ("v_writelane_b32", manual_v_ops::v_writelane_b32),
  ("v_xad_u32", manual_v_ops::v_xad_u32),
  ("v_xnor_b32", manual_v_ops::v_xnor_b32),
  ("v_xor3_b32", manual_v_ops::v_xor3_b32),
  ("v_xor_b16", manual_v_ops::v_xor_b16),
  ("v_xor_b32", manual_v_ops::v_xor_b32),
];

pub static TYPED_OPS: &[(&str, TypedHandler)] = &[
  ("buffer_atomic_add_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("buffer_atomic_add_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("buffer_atomic_add_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("buffer_atomic_dec_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("buffer_atomic_dec_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("buffer_atomic_inc_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("buffer_atomic_inc_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("buffer_atomic_max_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("buffer_atomic_max_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("buffer_atomic_max_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("buffer_atomic_max_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("buffer_atomic_min_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("buffer_atomic_min_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("buffer_atomic_min_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("buffer_atomic_min_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("buffer_atomic_sub_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("buffer_atomic_sub_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_add_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("ds_add_rtn_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("ds_add_rtn_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_add_rtn_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_add_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_add_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_dec_rtn_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_dec_rtn_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_dec_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_dec_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_inc_rtn_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_inc_rtn_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_inc_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_inc_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_load_i16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I16 })),
  ("ds_load_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("ds_load_u16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U16 })),
  ("ds_load_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("ds_max_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("ds_max_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("ds_max_rtn_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("ds_max_rtn_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("ds_max_rtn_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_max_rtn_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_max_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_max_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_min_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("ds_min_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("ds_min_rtn_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("ds_min_rtn_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("ds_min_rtn_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_min_rtn_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_min_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_min_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_rsub_rtn_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_rsub_rtn_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_rsub_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_rsub_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_sub_rtn_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_sub_rtn_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("ds_sub_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("ds_sub_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("flat_atomic_add_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("flat_atomic_add_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("flat_atomic_add_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("flat_atomic_dec_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("flat_atomic_dec_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("flat_atomic_inc_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("flat_atomic_inc_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("flat_atomic_max_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("flat_atomic_max_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("flat_atomic_max_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("flat_atomic_max_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("flat_atomic_min_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("flat_atomic_min_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("flat_atomic_min_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("flat_atomic_min_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("flat_atomic_sub_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("flat_atomic_sub_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("flat_load_d16_hi_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("flat_load_d16_hi_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("flat_load_d16_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("flat_load_d16_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("flat_load_i16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I16 })),
  ("flat_load_i8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I8 })),
  ("flat_load_u16", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U16 })),
  ("flat_load_u8", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U8 })),
  ("global_atomic_add_f32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::F32 })),
  ("global_atomic_add_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("global_atomic_add_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("global_atomic_dec_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("global_atomic_dec_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("global_atomic_inc_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("global_atomic_inc_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("global_atomic_max_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("global_atomic_max_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("global_atomic_max_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("global_atomic_max_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("global_atomic_min_i32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I32 })),
  ("global_atomic_min_i64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::I64 })),
  ("global_atomic_min_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("global_atomic_min_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("global_atomic_sub_u32", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U32 })),
  ("global_atomic_sub_u64", TypedHandler::Mem(TypedMemHandler::Unknown { dtype: DataType::U64 })),
  ("s_ashr_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_ashr_i64", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I64 })),
  ("s_bfe_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_bfe_i64", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I64 })),
  ("s_bfe_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_bfe_u64", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U64 })),
  ("s_clz_i32_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_clz_i32_u64", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U64 })),
  ("s_cmp_eq_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmp_eq_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmp_eq_u64", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U64 })),
  ("s_cmp_ge_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmp_ge_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmp_gt_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmp_gt_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmp_le_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmp_le_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmp_lg_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmp_lg_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_cmp_lg_u64", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U64 })),
  ("s_cmp_lt_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_cmp_lt_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_max_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_max_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_min_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_min_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_mul_hi_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_mul_hi_u32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::U32 })),
  ("s_mul_i32", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I32 })),
  ("s_sext_i32_i16", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I16 })),
  ("s_sext_i32_i8", TypedHandler::S(TypedSHandler::Unknown { dtype: DataType::I8 })),
  ("v_add_f16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F16, op: BinaryOp::Add })),
  ("v_add_f32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F32, op: BinaryOp::Add })),
  ("v_add_nc_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_add_nc_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_add_nc_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_add_nc_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_ashrrev_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_ashrrev_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_ashrrev_i64", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I64 })),
  ("v_bfe_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_bfe_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_ceil_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_ceil_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmp_class_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cmp_class_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmp_eq_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_eq_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_eq_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_eq_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_eq_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_eq_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_eq_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_eq_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Eq, update_exec: false })),
  ("v_cmp_ge_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_ge_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_ge_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_ge_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_ge_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_ge_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_ge_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_ge_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Ge, update_exec: false })),
  ("v_cmp_gt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_gt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_gt_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_gt_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_gt_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_gt_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_gt_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_gt_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Gt, update_exec: false })),
  ("v_cmp_le_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_le_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_le_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_le_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_le_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_le_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_le_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_le_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Le, update_exec: false })),
  ("v_cmp_lg_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Lg, update_exec: false })),
  ("v_cmp_lg_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Lg, update_exec: false })),
  ("v_cmp_lt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_lt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_lt_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_lt_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_lt_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_lt_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_lt_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_lt_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Lt, update_exec: false })),
  ("v_cmp_ne_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Ne, update_exec: false })),
  ("v_cmp_ne_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Ne, update_exec: false })),
  ("v_cmp_ne_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Ne, update_exec: false })),
  ("v_cmp_ne_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Ne, update_exec: false })),
  ("v_cmp_ne_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Ne, update_exec: false })),
  ("v_cmp_ne_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Ne, update_exec: false })),
  ("v_cmp_neq_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Neq, update_exec: false })),
  ("v_cmp_neq_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Neq, update_exec: false })),
  ("v_cmp_nge_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nge, update_exec: false })),
  ("v_cmp_nge_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nge, update_exec: false })),
  ("v_cmp_ngt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Ngt, update_exec: false })),
  ("v_cmp_ngt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Ngt, update_exec: false })),
  ("v_cmp_nle_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nle, update_exec: false })),
  ("v_cmp_nle_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nle, update_exec: false })),
  ("v_cmp_nlg_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nlg, update_exec: false })),
  ("v_cmp_nlg_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nlg, update_exec: false })),
  ("v_cmp_nlt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nlt, update_exec: false })),
  ("v_cmp_nlt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nlt, update_exec: false })),
  ("v_cmp_o_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::O, update_exec: false })),
  ("v_cmp_o_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::O, update_exec: false })),
  ("v_cmp_u_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::U, update_exec: false })),
  ("v_cmp_u_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::U, update_exec: false })),
  ("v_cmpx_class_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cmpx_class_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cmpx_eq_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_eq_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_eq_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_eq_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_eq_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_eq_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_eq_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_eq_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Eq, update_exec: true })),
  ("v_cmpx_ge_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_ge_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_ge_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_ge_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_ge_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_ge_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_ge_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_ge_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Ge, update_exec: true })),
  ("v_cmpx_gt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_gt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_gt_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_gt_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_gt_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_gt_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_gt_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_gt_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Gt, update_exec: true })),
  ("v_cmpx_le_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_le_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_le_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_le_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_le_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_le_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_le_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_le_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Le, update_exec: true })),
  ("v_cmpx_lg_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Lg, update_exec: true })),
  ("v_cmpx_lg_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Lg, update_exec: true })),
  ("v_cmpx_lt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_lt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_lt_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_lt_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_lt_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_lt_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_lt_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_lt_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Lt, update_exec: true })),
  ("v_cmpx_ne_i16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I16, op: CmpOp::Ne, update_exec: true })),
  ("v_cmpx_ne_i32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I32, op: CmpOp::Ne, update_exec: true })),
  ("v_cmpx_ne_i64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::I64, op: CmpOp::Ne, update_exec: true })),
  ("v_cmpx_ne_u16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U16, op: CmpOp::Ne, update_exec: true })),
  ("v_cmpx_ne_u32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U32, op: CmpOp::Ne, update_exec: true })),
  ("v_cmpx_ne_u64", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::U64, op: CmpOp::Ne, update_exec: true })),
  ("v_cmpx_neq_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Neq, update_exec: true })),
  ("v_cmpx_neq_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Neq, update_exec: true })),
  ("v_cmpx_nge_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nge, update_exec: true })),
  ("v_cmpx_nge_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nge, update_exec: true })),
  ("v_cmpx_ngt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Ngt, update_exec: true })),
  ("v_cmpx_ngt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Ngt, update_exec: true })),
  ("v_cmpx_nle_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nle, update_exec: true })),
  ("v_cmpx_nle_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nle, update_exec: true })),
  ("v_cmpx_nlg_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nlg, update_exec: true })),
  ("v_cmpx_nlg_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nlg, update_exec: true })),
  ("v_cmpx_nlt_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::Nlt, update_exec: true })),
  ("v_cmpx_nlt_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::Nlt, update_exec: true })),
  ("v_cmpx_o_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::O, update_exec: true })),
  ("v_cmpx_o_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::O, update_exec: true })),
  ("v_cmpx_u_f16", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F16, op: CmpOp::U, update_exec: true })),
  ("v_cmpx_u_f32", TypedHandler::V(TypedVHandler::Cmp { dtype: DataType::F32, op: CmpOp::U, update_exec: true })),
  ("v_cos_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cos_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_f16_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_f16_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_cvt_f16_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_cvt_f32_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cvt_f32_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_cvt_f32_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_cvt_i32_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_i32_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_cvt_pk_i16_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_pk_i16_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_cvt_pk_norm_i16_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cvt_pk_norm_i16_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_pk_norm_u16_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_cvt_pk_norm_u16_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_pk_u16_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_pk_u16_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_cvt_u32_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_cvt_u32_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_div_fixup_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_div_fixup_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_dot2_f32_bf16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::BF16 })),
  ("v_dot2_f32_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_dual_dot2acc_f32_bf16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::BF16 })),
  ("v_dual_dot2acc_f32_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_exp_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_exp_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_floor_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_floor_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_fma_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_fma_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_fmaak_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_fmaak_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_fmac_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_fmac_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_fmamk_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_fmamk_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_fract_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_fract_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_frexp_mant_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_frexp_mant_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_ldexp_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_ldexp_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_log_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_log_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_mad_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_mad_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_max3_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_max3_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_max3_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_max3_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_max_i16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::I16, op: BinaryOp::Max })),
  ("v_max_i32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::I32, op: BinaryOp::Max })),
  ("v_max_u16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::U16, op: BinaryOp::Max })),
  ("v_max_u32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::U32, op: BinaryOp::Max })),
  ("v_maxmin_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_maxmin_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_med3_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_med3_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_med3_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_med3_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_min3_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_min3_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_min3_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_min3_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_min_i16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::I16, op: BinaryOp::Min })),
  ("v_min_i32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::I32, op: BinaryOp::Min })),
  ("v_min_u16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::U16, op: BinaryOp::Min })),
  ("v_min_u32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::U32, op: BinaryOp::Min })),
  ("v_minmax_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_minmax_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_mul_f16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F16, op: BinaryOp::Mul })),
  ("v_mul_f32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F32, op: BinaryOp::Mul })),
  ("v_mul_hi_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_mul_hi_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_mul_lo_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_mul_lo_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_pk_add_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_pk_add_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_pk_add_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_pk_mad_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_pk_mad_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_pk_max_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_pk_max_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_pk_min_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_pk_min_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_pk_sub_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_pk_sub_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_rcp_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_rcp_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_rndne_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_rndne_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_rsq_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_rsq_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_sad_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_sad_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_sad_u8", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U8 })),
  ("v_sin_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_sin_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_sqrt_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_sqrt_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_sub_f16", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F16, op: BinaryOp::Sub })),
  ("v_sub_f32", TypedHandler::V(TypedVHandler::Binary { dtype: DataType::F32, op: BinaryOp::Sub })),
  ("v_sub_nc_i16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I16 })),
  ("v_sub_nc_i32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::I32 })),
  ("v_sub_nc_u16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U16 })),
  ("v_sub_nc_u32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::U32 })),
  ("v_subrev_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_subrev_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_trunc_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
  ("v_trunc_f32", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F32 })),
  ("v_wmma_f32_16x16x16_bf16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::BF16 })),
  ("v_wmma_f32_16x16x16_f16", TypedHandler::V(TypedVHandler::Unknown { dtype: DataType::F16 })),
];
